# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 756)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1211, 751))
        self.tabWidget.setObjectName("tabWidget")
        self.gallery_tab = QtWidgets.QWidget()
        self.gallery_tab.setObjectName("gallery_tab")
        self.gallery_list = QtWidgets.QListWidget(parent=self.gallery_tab)
        self.gallery_list.setGeometry(QtCore.QRect(0, 0, 891, 721))
        self.gallery_list.setObjectName("gallery_list")
        self.tabWidget.addTab(self.gallery_tab, "")
        self.add_games_tab = QtWidgets.QWidget()
        self.add_games_tab.setObjectName("add_games_tab")
        self.open_games_list = QtWidgets.QListWidget(parent=self.add_games_tab)
        self.open_games_list.setGeometry(QtCore.QRect(0, 40, 521, 661))
        self.open_games_list.setObjectName("open_games_list")
        self.add_game_btn = QtWidgets.QPushButton(parent=self.add_games_tab)
        self.add_game_btn.setGeometry(QtCore.QRect(540, 50, 121, 41))
        self.add_game_btn.setObjectName("add_game_btn")
        self.remove_game_btn = QtWidgets.QPushButton(parent=self.add_games_tab)
        self.remove_game_btn.setGeometry(QtCore.QRect(540, 180, 121, 41))
        self.remove_game_btn.setObjectName("remove_game_btn")
        self.games_to_watch_list = QtWidgets.QListWidget(parent=self.add_games_tab)
        self.games_to_watch_list.setGeometry(QtCore.QRect(680, 40, 521, 661))
        self.games_to_watch_list.setObjectName("games_to_watch_list")
        self.open_procs_label = QtWidgets.QLabel(parent=self.add_games_tab)
        self.open_procs_label.setGeometry(QtCore.QRect(130, 20, 151, 16))
        self.open_procs_label.setObjectName("open_procs_label")
        self.games_to_watch_label = QtWidgets.QLabel(parent=self.add_games_tab)
        self.games_to_watch_label.setGeometry(QtCore.QRect(890, 20, 151, 16))
        self.games_to_watch_label.setObjectName("games_to_watch_label")
        self.tabWidget.addTab(self.add_games_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.tabWidget.addTab(self.settings_tab, "")
        self.logs_tab = QtWidgets.QWidget()
        self.logs_tab.setObjectName("logs_tab")
        self.logOutput = QtWidgets.QPlainTextEdit(parent=self.logs_tab)
        self.logOutput.setGeometry(QtCore.QRect(0, 0, 1201, 721))
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.tabWidget.addTab(self.logs_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gallery_tab), _translate("MainWindow", "Gallery"))
        self.add_game_btn.setText(_translate("MainWindow", "Add Game"))
        self.remove_game_btn.setText(_translate("MainWindow", "Remove Game"))
        self.open_procs_label.setText(_translate("MainWindow", "Open Processes"))
        self.games_to_watch_label.setText(_translate("MainWindow", "Games to watch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_games_tab), _translate("MainWindow", "Add Games"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logs_tab), _translate("MainWindow", "Logs"))
